# Generated by Django 4.0.5 on 2022-06-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_gen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_details',
            name='event_end_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event_details',
            name='event_start_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event_details',
            name='organizer',
            field=models.CharField(blank=True, default='None', max_length=150, null=True),
        ),
    ]
