# Generated by Django 4.0.5 on 2022-06-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_gen', '0002_alter_event_details_event_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signs',
            name='digital_Signatures',
            field=models.ImageField(blank=True, max_length=15, null=True, upload_to=''),
        ),
    ]
